In [8]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [9]:
df = pd.read_csv("../data/cleaned_data.csv")
df.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [10]:
df.isnull().sum()

Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

# Feature Engineering

In [12]:
# To check someone earning 5k and asking for 50k loan = risky
df['Loan_to_Income'] = df['LoanAmount'] / df['Income']

In [13]:
# High credit lines + low income = risky
df['Income_per_CreditLine'] = df['Income'] / (df['NumCreditLines'] + 1)

In [14]:
# Stable Employment = Stable Candidate
df['Employment_Stability'] = df['MonthsEmployed'] / (df['Age'] + 1)

In [15]:
# Higher Interest = High Pressure = Risky
df['Interest_Burden'] = df['LoanAmount'] * df['InterestRate']

In [16]:
df.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,...,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default,Loan_to_Income,Income_per_CreditLine,Employment_Stability,Interest_Burden
0,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,...,Divorced,Yes,Yes,Other,Yes,0,0.588262,17198.80,1.403509,770440.01
1,69,50432,124440,458,15,1,4.81,60,0.68,Master's,...,Married,No,No,Other,Yes,0,2.467481,25216.00,0.214286,598556.40
2,46,84208,129188,451,26,3,21.17,24,0.31,Master's,...,Divorced,Yes,Yes,Auto,No,1,1.534154,21052.00,0.553191,2734909.96
3,32,31713,44799,743,0,3,7.07,24,0.23,High School,...,Married,No,No,Business,No,0,1.412638,7928.25,0.000000,316728.93
4,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,...,Divorced,No,Yes,Auto,No,0,0.447179,4087.40,0.131148,59494.89

In [17]:
df.shape

(255347, 21)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Age                    255347 non-null  int64
 1   Income                 255347 non-null  int64
 2   LoanAmount             255347 non-null  int64
 3   CreditScore            255347 non-null  int64
 4   MonthsEmployed         255347 non-null  int64
 5   NumCreditLines         255347 non-null  int64
 6   InterestRate           255347 non-null  float64
 7   LoanTerm               255347 non-null  int64
 8   DTIRatio               255347 non-null  float64
 9   Education              255347 non-null  str
 10  EmploymentType         255347 non-null  str
 11  MaritalStatus          255347 non-null  str
 12  HasMortgage            255347 non-null  str
 13  HasDependents          255347 non-null  str
 14  LoanPurpose            255347 non-null  str
 15  HasCoSigner            255347 non-null  str
 16  Default                255347 non-null  int64
 17  Loan_to_Income         255347 non-null  float64
 18  Income_per_CreditLine  255347 non-null  float64
 19  Employment_Stability   255347 non-null  float64
 20  Interest_Burden        255347 non-null  float64
dtypes: float64(6), int64(8), str(7)
memory usage: 50.4 MB

In [19]:
# Feature Encoding
df = pd.get_dummies(df, drop_first=True, dtype=int)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 29 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Age                           255347 non-null  int64
 1   Income                        255347 non-null  int64
 2   LoanAmount                    255347 non-null  int64
 3   CreditScore                   255347 non-null  int64
 4   MonthsEmployed                255347 non-null  int64
 5   NumCreditLines                255347 non-null  int64
 6   InterestRate                  255347 non-null  float64
 7   LoanTerm                      255347 non-null  int64
 8   DTIRatio                      255347 non-null  float64
 9   Default                       255347 non-null  int64
 10  Loan_to_Income                255347 non-null  float64
 11  Income_per_CreditLine         255347 non-null  float64
 12  Employment_Stability          255347 non-null  float64
 13  Interest_Burden               255347 non-null  float64
 14  Education_High School         255347 non-null  int64
 15  Education_Master's            255347 non-null  int64
 16  Education_PhD                 255347 non-null  int64
 17  EmploymentType_Part-time      255347 non-null  int64
 18  EmploymentType_Self-employed  255347 non-null  int64
 19  EmploymentType_Unemployed     255347 non-null  int64
 20  MaritalStatus_Married         255347 non-null  int64
 21  MaritalStatus_Single          255347 non-null  int64
 22  HasMortgage_Yes               255347 non-null  int64
 23  HasDependents_Yes             255347 non-null  int64
 24  LoanPurpose_Business          255347 non-null  int64
 25  LoanPurpose_Education         255347 non-null  int64
 26  LoanPurpose_Home              255347 non-null  int64
 27  LoanPurpose_Other             255347 non-null  int64
 28  HasCoSigner_Yes               255347 non-null  int64
dtypes: float64(6), int64(23)
memory usage: 56.5 MB

In [21]:
df.to_csv("../data/processed_data.csv", index=False)